# BEFORE PUSHING, CHECK TO MINIFY THE FILES FOR NPM

name: 'Publish to NPM'

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Publish to NPM
        run: |
          cd npm_pkg_min
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_GITHUB_PP_CLI}}
